### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by kdewitt** [Volition21/BlockTrackR#3]
I set up a new Sponge server this morning and am getting the attached error.  I've removed CraftBook and am still seeing the error.  There are no other plugins.  I realize this is all still in alpha/beta, just thought I'd bring this to your attention.

![2015-07-12_08-26-18](https://cloud.githubusercontent.com/assets/740342/8638434/fd5ed612-286f-11e5-99f7-7deceec5ab1e.png)
![2015-07-12_08-24-37](https://cloud.githubusercontent.com/assets/740342/8638437/1eb93424-2870-11e5-9146-e6f66da5e7cf.png)

**Comment by nalimleinad** [comment]
Access denined...
Plugin cannot connect to your database. Chceck your connection settings.

**Comment by Volition21** [comment]
Issue lies w/ end-user sql config.
