### ISSUE TITLE
Exception while running /btr auth and the playername contains an underscore

### ISSUE THREAD

**Issue by JoeSchmo2840** [Volition21/BlockTrackR#4]
I was running /btr auth _cIark100101314

15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.Volition21.BlockTrackR.Command.BTRAuthCommand$1.run(BTRAuthCommand.java:74)
15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.Volition21.BlockTrackR.Command.BTRAuthCommand.authorizeUser(BTRAuthCommand.java:102)
15.07 02:46:14 [Server] BTRAC/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.Volition21.BlockTrackR.Utility.BTRConfiguration.authorizeUser(BTRConfiguration.java:71)
15.07 02:46:14 [Server] INFO Exception in thread "BTRAC" [02:46:14] [BTRAC/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: org/apache/commons/lang/ArrayUtils

**Comment by nalimleinad** [comment]
I have got some problems ( java.lang.NoClassDefFoundError) with ArrayUtils from external library too.

**Comment by Volition21** [comment]
Replaced the whole block of code with something a little less over the place. Removes those dependencies all together so I'm going to consider this issue resolved. Please note I have not had the chance to test it, the build of the API I am working with is too new compared to released builds of the Sponge binary - Expect a bug, hope for none.
