### ISSUE TITLE
Using Sponge 833 - Event displaying issues

### ISSUE THREAD

**Issue by KumaGetsu** [Volition21/BlockTrackR#9]
PlayerChatEvent - Does not record commands
PlayerDropItemEvent - Does not display items drop
PlayerPickupItemEvent - Does not display items pickup
PlayerJoinEvent - Displays this for players joined "You are not allowed to log in to this server."

**Comment by Volition21** [comment]
I should refactor this shit. Give me a few hours.

**Comment by Volition21** [comment]
Alright done, not done, not done, done.

Added Command logging
Shoved in a stopgap for "You are not allowed to log in to this server."

Todo:
Fix chat properly.
